import { Meta, Story } from '@storybook/react'
import { WithTranslation, withTranslation } from 'react-i18next'
import styled from '@emotion/styled'
import { Grid, Typography } from '@mui/material'
import {
  ActiveIcon,
  AddIcon,
  AlertIcon,
  AmmRankIcon,
  ApprovalIcon,
  AssetsIcon,
  AudioIcon,
  BackIcon,
  BanxaIcon,
  CalendarIcon,
  CardIcon,
  CheckBoxIcon,
  CheckedIcon,
  CheckIcon,
  CircleIcon,
  ClockIcon,
  CloseIcon,
  CloseRedPacketIcon,
  CompleteIcon,
  ContactIcon,
  ConvertToIcon,
  CopyIcon,
  DarkIcon,
  DeleteIcon,
  DepositIcon,
  DepthFIcon,
  DepthHIcon,
  DiscordIcon,
  DoneIcon,
  DownloadIcon,
  DragIcon,
  DragListIcon,
  DropDownIcon,
  EditIcon,
  EmptyIcon,
  ErrorIcon,
  ExchangeAIcon,
  ExchangeIcon,
  ExitIcon,
  FailedIcon,
  FavHollowIcon,
  FavSolidIcon,
  FirstPlaceIcon,
  GoodIcon,
  GoTopIcon,
  GrowIcon,
  HelpIcon,
  HideIcon,
  ImageIcon,
  IncomingIcon,
  Info2Icon,
  InfoIcon,
  KLineFeaturesIcon,
  L1l2Icon,
  L2HistoryIcon,
  L2l2Icon,
  L2MyLiquidityIcon,
  L2OrderIcon,
  LegacyIcon,
  LightIcon,
  LinkedIcon,
  LinkIcon,
  LoadingIcon,
  LockGuardianIcon,
  LockIcon,
  LoopringDarkFooterIcon,
  LoopringIcon,
  LoopringLightFooterIcon,
  LoopringLogoIcon,
  MediumIcon,
  MenuIcon,
  MintIcon,
  MoreIcon,
  NFTIcon,
  NoPhotosIcon,
  NotificationIcon,
  OrderListIcon,
  OutputIcon,
  PlayIcon,
  ProfileIcon,
  ProToLiteIcon,
  QRIcon,
  RampIcon,
  RecordIcon,
  RedPacketIcon,
  RefreshIcon,
  RefreshIPFSIcon,
  RefuseIcon,
  ResizeIcon,
  ReverseIcon,
  RewardIcon,
  RoundAddIcon,
  ScanQRIcon,
  SearchIcon,
  SecondPlaceIcon,
  SecurityIcon,
  SettingIcon,
  SpeakerIcon,
  StarHollowIcon,
  StarSolidIcon,
  SubmitIcon,
  SwapSettingIcon,
  SyncIcon,
  ThirdPlaceIcon,
  TransferIcon,
  TrophyIcon,
  TwitterIcon,
  UnConnectIcon,
  UpIcon,
  UploadedIcon,
  VideoIcon,
  ViewHistoryIcon,
  ViewIcon,
  ViewMoreIcon,
  VipIcon,
  WaitApproveIcon,
  WaitingIcon,
  WarningIcon,
  WarningIcon2,
  WithdrawIcon,
  YoutubeIcon,
  ZoomIcon,
  RiskAlertIcon,
  RiskIcon,
  AnotherIcon,
  LinkSharedIcon,
  ReadIcon,
  MessageIcon,
  GoIcon,
} from '@loopring-web/common-resources'

const Styled = styled.div`
  background: var(--color-global-bg);

  svg {
    height: 24px;
    width: 24px;
  }
`

// @ts-ignore
const listIcon = [
  <DepthHIcon />,
  <DepthFIcon />,
  <UpIcon />,
  <DragIcon />,
  <DragListIcon />,
  <ResizeIcon />,
  <AssetsIcon />,
  <L2MyLiquidityIcon />,
  <L2HistoryIcon />,
  <RewardIcon />,
  <RedPacketIcon />,
  <SecurityIcon />,
  <VipIcon />,
  <L2OrderIcon />,
  <CheckBoxIcon />,
  <CheckedIcon />,
  <ViewIcon />,
  <HideIcon />,
  <DropDownIcon />,
  <BackIcon />,
  <MoreIcon />,
  <StarHollowIcon />,
  <StarSolidIcon />,
  <DownloadIcon />,
  <NotificationIcon />,
  <SettingIcon />,
  <LinkIcon />,
  <CopyIcon />,
  <ReverseIcon />,
  <HelpIcon />,
  <CalendarIcon />,
  <LinkedIcon />,
  <ExchangeIcon />,
  <CloseIcon />,
  <SearchIcon />,
  <MenuIcon />,
  <QRIcon />,
  <DoneIcon />,
  <RefuseIcon />,
  <SubmitIcon />,
  <FailedIcon />,
  <GoodIcon />,
  <AlertIcon />,
  <ErrorIcon />,
  <InfoIcon />,
  <UnConnectIcon />,
  <LockIcon />,
  <ProToLiteIcon />,
  <CheckIcon />,
  <LoadingIcon />,
  <ActiveIcon />,
  <RefreshIcon />,
  <CompleteIcon />,
  <WaitingIcon />,
  <WarningIcon />,
  <EmptyIcon />,
  <CircleIcon />,
  <GrowIcon />,
  <NoPhotosIcon />,
  <KLineFeaturesIcon />,
  <LoopringDarkFooterIcon />,
  <LoopringLightFooterIcon />,
  <YoutubeIcon />,
  <TwitterIcon />,
  <MediumIcon />,
  <DiscordIcon />,
  <LoopringIcon />,
  <LightIcon />,
  <DarkIcon />,
  <ExitIcon />,
  <RampIcon />,
  <BanxaIcon />,
  <FirstPlaceIcon />,
  <SecondPlaceIcon />,
  <ThirdPlaceIcon />,
  <TrophyIcon />,
  <AmmRankIcon />,
  <SpeakerIcon />,
  <GoTopIcon />,
  <NFTIcon />,
  <RecordIcon />,
  <WaitApproveIcon />,
  <LoopringLogoIcon />,
  <TransferIcon />,
  <DepositIcon />,
  <WithdrawIcon />,
  <MintIcon />,
  <AddIcon />,
  <DeleteIcon />,
  <ImageIcon />,
  <Info2Icon />,
  <IncomingIcon />,
  <OutputIcon />,
  <CardIcon />,
  <L2l2Icon />,
  <L1l2Icon />,
  <ExchangeAIcon />,
  <AudioIcon />,
  <VideoIcon />,
  <PlayIcon />,
  <ProfileIcon />,
  <OrderListIcon />,
  <RefreshIPFSIcon />,
  <ViewMoreIcon />,
  <ZoomIcon />,
  <LegacyIcon />,
  <SyncIcon />,
  <FavHollowIcon />,
  <FavSolidIcon />,
  <SwapSettingIcon />,
  <WarningIcon2 />,
  <RoundAddIcon />,
  <ApprovalIcon />,
  <LockGuardianIcon />,
  <ViewHistoryIcon />,
  <ScanQRIcon />,
  <CloseRedPacketIcon />,
  <ClockIcon />,
  <ContactIcon />,
  <UploadedIcon />,
  <EditIcon />,
  <ConvertToIcon />,
  <RiskAlertIcon />,
  <RiskIcon />,
  <AnotherIcon />,
  <LinkSharedIcon />,
  <ReadIcon />,
  <MessageIcon />,
  <GoIcon />,
]

export const IconList: Story<any> = withTranslation()(({}: WithTranslation & any) => {
  const view = listIcon.map((item, index) => {
    return (
      <Grid
        key={index}
        item
        padding={2}
        display={'flex'}
        flexDirection={'column'}
        alignItems={'center'}
      >
        {item}
        <Typography padding={1} variant={'body2'}>
          {item.type.name}
        </Typography>
      </Grid>
    )
  })

  return (
    <>
      <Styled>
        {/*<MemoryRouter initialEntries={['/']}>*/}
        <Grid container>{view}</Grid>
      </Styled>
      {/*</MemoryRouter>*/}
    </>
  )
}) as Story<any>

//export const Button = Template.bind({});
// @ts-ignore
export default {
  title: 'Resource/IconsList',
  component: IconList,
  argTypes: {},
} as Meta
// LButton.args = {}
